apps/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import register_user


app_name = 'authentication'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

apps/core/urls.py
from .views import index_page, about_page
from django.urls import path


# naming app
app_name = 'core'
urlpatterns = [
    path('', index_page, name='index'),
    path('about/', about_page, name='about')
]

apps/dashboard/urls.py
from .views import dashboard_page
from django.urls import path


app_name = 'dashboard'
urlpatterns = [
    path('', dashboard_page, name='main'),
]

apps/leads/urls.py
from .views import (
    lead_add, lead_list,
    lead_detail, lead_delete,
    lead_edit, convert_to_client
)
from django.urls import path


app_name = 'leads'
urlpatterns = [
    path('', lead_list, name='list'),
    path('add/', lead_add, name='add'),
    path('<int:pk>/convert-to-client/',
         convert_to_client, name='convert-to-client'),
    path('<int:pk>/detail/', lead_detail, name='detail'),
    path('<int:pk>/edit/', lead_edit, name='edit'),
    path('<int:pk>/delete/', lead_delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls', namespace='core')),
    path('auth/', include('apps.authentication.urls', namespace='authentication')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('lead/', include('apps.leads.urls', namespace='leads')),
    path('client/', include('apps.client.urls', namespace='client')),
    path("admin/", admin.site.urls),
]

apps/core/views.py
from django.shortcuts import render


def index_page(request):
    return render(request, 'core/index.html')


def about_page(request):
    return render(request, 'core/about.html')

apps/core/templates/components/footer.html
<footer class="py-8 bg-gray-200 text-center">
  <p class="text-xs text-gray-700">Copyright(c) 2023 - CRM System</p>
</footer>

apps/core/templates/components/messages.html
{% if messages %}
<div class="py-6 px-6">
  {% for message in messages %}
  <div
    class="py-4 px-4 bg-teal-700 text-white rounded-xl font-semibold text-xl"
  >
    {{message}}
  </div>
  {% endfor %}
</div>
{% endif %}

apps/core/templates/components/navbar.html
<nav class="py-4 px-6 flex justify-between bg-teal-500">
  <a href="/" class="uppercase py-2 px-6 text-white">crm app</a>
  <div class="flex space-x-2">
    <a href="{% url 'core:about' %}" class="text-white py-2 px-6 rounded-xl"
      >about</a
    >
    {% if not request.user.is_authenticated %}
    <a
      href="{% url 'authentication:login' %}"
      class="text-white py-2 px-6 bg-teal-700 rounded-xl"
      >Login</a
    >
    <a
      href="{% url 'authentication:register' %}"
      class="text-white py-2 px-6 bg-teal-300 rounded-xl"
      >register</a
    >
    {% else %}
    <a
      href="{% url 'client:list' %}"
      class="text-white py-2 px-6 bg-teal-700 rounded-xl"
    >
      Client
    </a>
    <a
      href="{% url 'leads:list' %}"
      class="text-white py-2 px-6 bg-teal-700 rounded-xl"
    >
      Leads
    </a>
    <a
      href="{% url 'dashboard:main' %}"
      class="text-white py-2 px-6 bg-teal-700 rounded-xl"
      >Dashboard</a
    >
    <a
      href="{% url 'authentication:logout' %}"
      class="text-white py-2 px-6 bg-red-300 rounded-xl"
      >Logout</a
    >
    {% endif %}
  </div>
</nav>