apps/client/urls.py
from .views import (
    client_add, client_list, client_detail, client_edit, client_delete
)
from django.urls import path


app_name = 'client'
urlpatterns = [
    path('', client_list, name='list'),
    path('add/', client_add, name='add'),
    path('<int:pk>/detail/', client_detail, name='detail'),
    path('<int:pk>/edit/', client_edit, name='edit'),
    path('<int:pk>/delete/', client_delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls', namespace='core')),
    path('auth/', include('apps.authentication.urls', namespace='authentication')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('lead/', include('apps.leads.urls', namespace='leads')),
    path('client/', include('apps.client.urls', namespace='client')),
    path("admin/", admin.site.urls),
]

apps/client/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):

    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)

    create_by = models.ForeignKey(
        User, related_name='clients', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

apps/client/forms.py
from django import forms
from .models import Client


class AddClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'email', 'description')

apps/client/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AddClientForm
from .models import Client


@login_required
def client_add(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        if form.is_valid():
            client = form.save(commit=False)
            client.create_by = request.user
            client.save()
            messages.success(request, 'The Client wes created successfully')
            return redirect('client:list')
    else:
        form = AddClientForm()
    return render(request, 'client/add.html', {'form': form})


@login_required
def client_list(request):
    clients = Client.objects.filter(create_by=request.user)
    return render(request, 'client/list.html', {'clients': clients})


@login_required
def client_detail(request, pk):
    client = get_object_or_404(Client, create_by=request.user, pk=pk)
    return render(request, 'client/detail.html', {'client': client})


@login_required
def client_delete(request, pk):
    client = get_object_or_404(Client, create_by=request.user, pk=pk)
    client.delete()
    messages.success(request, 'The client wes deleted.')
    return redirect('client:list')


@login_required
def client_edit(request, pk):
    client = get_object_or_404(Client, create_by=request.user, pk=pk)
    if request.method == 'POST':
        form = AddClientForm(request.POST, instance=client)
        if form.is_valid():
            form.save()
            messages.success(request, 'The Lead wes update successfully')
            return redirect('client:detail', pk=client.id)
    else:
        form = AddClientForm(instance=client)
    return render(request, 'client/edit.html', {'form': form})

apps/client/templates/client/add.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %} Add Client {% endblock %}

<!-- content  -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="text-xl">Add new Client</h2>
  <form action="." method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="py-2 px-8 rounded-lg bg-teal-500 text-white">
      Add
    </button>
  </form>
</div>
{% endblock %}

apps/client/templates/client/detail.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} {{client.name}} {% endblock %}

<!-- content -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="mb-4 text-xl">{{client.name}}</h2>
  {% if client.description %}
  <p class="font-semibold">Description</p>
  <p class="mb-2">{{client.description}}</p>
  {% endif %}

  <hr class="my-4" />
  <a
    href="{% url 'client:edit' client.id %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-500 rounded-xl"
    >edit</a
  >
  <a
    href="{% url 'client:delete' client.id %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-red-500 rounded-xl"
    >delete</a
  >
  <hr class="my-4" />
  <a
    href="{% url 'client:list' %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-500 rounded-xl"
    >Back to Clients</a
  >
</div>
{% endblock %}

apps/client/templates/client/edit.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %} edit Client: {{client.name}} {% endblock %}

<!-- content  -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="text-xl">edit Client: {{client.name}}</h2>
  <form action="." method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="py-2 px-8 rounded-lg bg-teal-500 text-white">
      update
    </button>
  </form>
</div>
{% endblock %}

apps/client/templates/client/list.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Clients List {% endblock %}

<!-- content -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="mb-4 text-xl">Clients List</h2>
  <div class="mt-6 py-4 flex justify-between">
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Client Name</p>
  </div>
  {% for client in clients %}
  <div class="flex justify-between">
    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
      <a href="{% url 'client:detail' client.id %}">{{client.name}}</a>
    </p>
  </div>
  {% empty %}
  <p class="py-2 px-4">There are no client in database yet...</p>
  {% endfor %}
  <a
    href="{% url 'client:add' %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-700 rounded-xl"
    >Add Client</a
  >
</div>
{% endblock %}