apps/leads/urls.py
from .views import (
    lead_add, lead_list,
    lead_detail, lead_delete,
    lead_edit, convert_to_client
)
from django.urls import path


app_name = 'leads'
urlpatterns = [
    path('', lead_list, name='list'),
    path('add/', lead_add, name='add'),
    path('<int:pk>/convert-to-client/',
         convert_to_client, name='convert-to-client'),
    path('<int:pk>/detail/', lead_detail, name='detail'),
    path('<int:pk>/edit/', lead_edit, name='edit'),
    path('<int:pk>/delete/', lead_delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls', namespace='core')),
    path('auth/', include('apps.authentication.urls', namespace='authentication')),
    path('dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    path('lead/', include('apps.leads.urls', namespace='leads')),
    path('client/', include('apps.client.urls', namespace='client')),
    path("admin/", admin.site.urls),
]

apps/leads/models.py
from django.db import models
from django.contrib.auth.models import User


class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )
    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'
    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost')
    )
    name = models.CharField(max_length=255)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=10, choices=CHOICES_STATUS, default=NEW)
    priority = models.CharField(
        max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    create_by = models.ForeignKey(
        User, related_name='leads', on_delete=models.CASCADE)
    converted_to_client = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

apps/leads/forms.py
from django import forms
from .models import Lead


class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name', 'email', 'description', 'priority', 'status')

apps/leads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import AddLeadForm
from .models import Lead
from apps.client.models import Client


@login_required
def lead_add(request):
    if request.method == 'POST':
        form = AddLeadForm(request.POST)
        if form.is_valid():
            lead = form.save(commit=False)
            lead.create_by = request.user
            lead.save()
            messages.success(request, 'The Lead wes created successfully')
            return redirect('leads:list')
    else:
        form = AddLeadForm()
    return render(request, 'leads/add.html', {'form': form})


@login_required
def lead_list(request):
    leads = Lead.objects.filter(
        create_by=request.user, converted_to_client=False)
    return render(request, 'leads/list.html', {'leads': leads})


@login_required
def lead_detail(request, pk):
    lead = get_object_or_404(Lead, create_by=request.user, pk=pk)
    return render(request, 'leads/detail.html', {'lead': lead})


@login_required
def lead_delete(request, pk):
    lead = get_object_or_404(Lead, create_by=request.user, pk=pk)
    lead.delete()
    messages.success(request, 'The Lead wes deleted.')
    return redirect('leads:list')


@login_required
def lead_edit(request, pk):
    lead = get_object_or_404(Lead, create_by=request.user, pk=pk)
    if request.method == 'POST':
        form = AddLeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            messages.success(request, 'The Lead wes update successfully')
            return redirect('leads:detail', pk=lead.id)
    else:
        form = AddLeadForm(instance=lead)
    return render(request, 'leads/edit.html', {'form': form})


@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, create_by=request.user, pk=pk)
    Client.objects.create(
        name=lead.name,
        email=lead.email,
        description=lead.description,
        create_by=request.user
    )
    lead.converted_to_client = True
    lead.save()
    return redirect('client:list')

apps/leads/templates/leads/add.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %} add lead {% endblock %}

<!-- content  -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="text-xl">Add new Lead</h2>
  <form action="." method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="py-2 px-8 rounded-lg bg-teal-500 text-white">
      Add
    </button>
  </form>
</div>
{% endblock %}

apps/leads/templates/leads/detail.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} {{lead.name}} {% endblock %}

<!-- content -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="mb-4 text-xl">{{lead.name}}</h2>
  {% if lead.description %}
  <p class="font-semibold">Description</p>
  <p class="mb-2">{{lead.description}}</p>
  {% endif %}
  <p class="font-semibold">Priority</p>
  <p class="mb-2">{{lead.get_priority_display}}</p>
  <p class="font-semibold">Status</p>
  <p class="mb-2">{{lead.get_status_display}}</p>
  <hr class="my-4" />
  <a
    href="{% url 'leads:convert-to-client' lead.id %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-blue-500 rounded-xl"
    >Convert to Client</a
  >
  <a
    href="{% url 'leads:edit' lead.id %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-500 rounded-xl"
    >edit</a
  >
  <a
    href="{% url 'leads:delete' lead.id %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-red-500 rounded-xl"
    >delete</a
  >
  <hr class="my-4" />
  <a
    href="{% url 'leads:list' %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-500 rounded-xl"
    >Back to Leads</a
  >
</div>
{% endblock %}

apps/leads/templates/leads/edit.html
{% extends 'base.html' %}

<!-- title block -->
{% block title %} edit lead: {{lead.name}} {% endblock %}

<!-- content  -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="text-xl">edit lead: {{lead.name}}</h2>
  <form action="." method="post">
    {% csrf_token %} {{form.as_p}}
    <button type="submit" class="py-2 px-8 rounded-lg bg-teal-500 text-white">
      update
    </button>
  </form>
</div>
{% endblock %}

apps/leads/templates/leads/list.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Leads List {% endblock %}

<!-- content -->
{% block content %}
<div class="py-6 px-6">
  <h2 class="mb-4 text-xl">Leads List</h2>
  <div class="mt-6 py-4 flex justify-between">
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Lead Name</p>
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
    <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
  </div>
  {% for lead in leads %}
  <div class="flex justify-between">
    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
      <a href="{% url 'leads:detail' lead.id %}">{{lead.name}}</a>
    </p>
    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
      {{lead.get_priority_display}}
    </p>
    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
      {{lead.get_status_display}}
    </p>
  </div>
  {% empty %}
  <p class="py-2 px-4">There are no lead in database yet...</p>
  {% endfor %}
  <a
    href="{% url 'leads:add' %}"
    class="mt-4 inline-block text-white py-2 px-6 bg-teal-700 rounded-xl"
    >Add Leads</a
  >
</div>
{% endblock %}